name: Update data

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 1 * *"

concurrency:
  group: update_data
  cancel-in-progress: true

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install NPM packages
        run: npm ci --legacy-peer-deps
      - name: Run tests
        run: npm run test-fetch
      - name: Fetch data
        run: npm run fetch
      - name: Upload data
        id: rsync01
        continue-on-error: true
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --omit-dir-times --no-owner --no-group --no-perms --delete
          path: static/data
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
      - name: Upload data (Retry if the 1st attempt fail)
        uses: burnett01/rsync-deployments@6.0.0
        if: steps.rsync01.outcome == 'failure'
        with:
          switches: -avzr --omit-dir-times --no-owner --no-group --no-perms --delete
          path: static/data
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
