name: Update data

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 1 * *'

concurrency:
  group: update_data
  cancel-in-progress: true

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Install NPM packages
      run: npm ci
    - name: Fetch data
      run: npm run fetch
    - name: Upload data
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: "static/data/*"
        target: ${{ secrets.DEPLOY_PATH }}
        overwrite: true
